#Ansible

- name: config name to Server vault
  ansible.builtin.shell: set-hostname vault

- name: config yum for Hashicorp vault
  ansible.builtin.shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: install vault
  ansible.builtin.dnf:
    name: vault
    state: present

- name: ReStart vault service
  ansible.builtin.systemd:
    name: vault
    state: restarted
    enabled: yes 